repos:
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
    -   id: commitizen
    -   id: commitizen-branch
        stages:
        - pre-push
-   repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --check --color always
        language: system
        pass_filenames: false
        stages:
        - pre-commit
      - id: tests
        name: tests
        description: Verify all tests pass
        entry: cargo test
        language: system
        pass_filenames: false
        stages:
        - pre-commit

